# user information
user:
  usrId: DEV-PC
  password: 8ik,(OL>
  birthdate: 1980-12-14 00:00:00
  sex: Male

# server information
server:
  ip: 192.168.100.106
  name: BRIAN-PCHOME

# logging information
logging:
  path: /user/local/log
  level:
    com:
      brian:
        springboot: INFO
    org:
      hibernate: ERROR

spring:
  # redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000ms
    # jedis client
    jedis:
      pool:
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
        max-active: 8
    # lettuce client
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
        max-active: 8
      shutdown-timeout: 100ms

  # database & jpa setup
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_demo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true


